import { createFileRoute } from '@tanstack/react-router'

import { card, container, primaryButton, secondaryButton } from '../ui'

const features = [
  ['Precursor-centered inspection', 'Add a peptide sequence and charge state, then inspect the targeted signal without processing the entire experiment.'],
  ['Interactive XIC views', 'Review precursor MS1 and fragment MS2 XICs with linear or log scale and optional TIC or base-peak overlays.'],
  ['iRT and charge prediction', 'Use model-based iRT and charge predictions to begin with a focused search window.'],
  ['Spectrum context', 'Compare experimental and predicted spectra alongside chromatographic evidence.'],
  ['Raw-file workspace', 'Keep local raw files, converted files, peptide lists, and analysis settings together.'],
  ['Exportable review', 'Export CSV results for notes, sharing, and downstream manual curation.'],
] as const

const workflow = ['Create a workspace', 'Add DIA raw files', 'Enter target precursors', 'Inspect MS1 and MS2 peak evidence'] as const

export const Route = createFileRoute('/spectralens')({
  head: () => ({ meta: [{ title: 'SpectraLens | Targeted DIA peak inspection' }] }),
  component: SpectraLensPage,
})

function SpectraLensPage() {
  return <>
    <section className="bg-linear-to-br from-cyan-50 to-blue-50 py-16 sm:py-24"><div className={`${container} grid items-center gap-12 lg:grid-cols-[1fr_1.05fr]`}><div><p className="mb-3 text-xs font-bold tracking-[.14em] text-brand uppercase">Targeted DIA peak inspection</p><h1 className="text-5xl font-semibold tracking-[-.045em] sm:text-6xl">SpectraLens</h1><p className="mt-5 text-xl leading-8 text-muted">Targeted DIA peak inspection for the precursor you care about.</p><p className="max-w-xl text-muted">Load raw files, enter a precursor, and inspect MS1/MS2 peak evidence without waiting for a full DIA pipeline.</p><div className="mt-8 flex flex-wrap gap-3"><a className={primaryButton} href="https://github.com/bionsight/SpectraLens/releases/tag/v0.4.5" target="_blank" rel="noreferrer">Download latest</a><a className={secondaryButton} href="#docs">Read docs</a></div></div><img className="rounded-2xl border border-cyan-200 shadow-2xl shadow-slate-900/15" src="/images/spectralens/spectralens_window.png" alt="SpectraLens desktop application showing precursor selection and XIC peak plots" /></div></section>
    <section className="bg-deep"><div className={`${container} grid gap-5 py-7 sm:grid-cols-2 lg:grid-cols-4`}>{[['Targeted', 'Precursor-first'], ['Views', 'MS1 and MS2 XIC'], ['Context', 'iRT, RT, spectra'], ['Output', 'CSV export']].map(([label, value]) => <div className="border-l border-white/20 pl-5 first:border-l-0 first:pl-0 max-sm:border-l-0 max-sm:pl-0" key={label}><span className="block text-xs tracking-[.12em] text-cyan-200 uppercase">{label}</span><strong className="text-white">{value}</strong></div>)}</div></section>
    <section className={`${container} py-16 sm:py-24`}><div className="mb-9 max-w-2xl"><p className="mb-3 text-xs font-bold tracking-[.14em] text-brand uppercase">Why it exists</p><h2 className="text-3xl font-semibold tracking-[-.035em] sm:text-4xl">Fast answers before a full analysis run</h2><p className="mb-0 text-muted">Focused visual confirmation for selected precursors and raw files.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(([title, text]) => <article className={card} key={title}><h3 className="text-lg font-semibold tracking-[-.025em]">{title}</h3><p className="mb-0 mt-3 text-sm leading-6 text-muted">{text}</p></article>)}</div></section>
    <section className="bg-deep py-16 sm:py-24"><div className={container}><div className="mb-9"><p className="mb-3 text-xs font-bold tracking-[.14em] text-cyan-200 uppercase">Workflow</p><h2 className="text-3xl font-semibold tracking-[-.035em] text-white sm:text-4xl">From raw file to peak evidence</h2></div><ol className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{workflow.map((step, index) => <li className="rounded-xl border border-white/20 p-5 text-slate-100" key={step}><span className="mb-3 block text-xs font-bold tracking-[.12em] text-cyan-200">0{index + 1}</span>{step}</li>)}</ol></div></section>
    <section id="docs" className={`${container} py-16 sm:py-24`}><div className="mb-9 max-w-2xl"><p className="mb-3 text-xs font-bold tracking-[.14em] text-brand uppercase">Docs</p><h2 className="text-3xl font-semibold tracking-[-.035em] sm:text-4xl">Install and use SpectraLens</h2></div><div className="grid gap-12 lg:grid-cols-[minmax(0,1.5fr)_minmax(17rem,.75fr)]"><article className="max-w-2xl text-muted [&_h3]:mt-8 [&_h3]:text-lg [&_h3]:font-semibold [&_h3]:tracking-[-.025em] [&_h3]:text-ink [&_li]:my-1 [&_li]:leading-7"><h3 className="mt-0!">Download</h3><p>SpectraLens is distributed as a local desktop app for macOS and Windows.</p><div className="mt-6 flex flex-wrap gap-3"><a className={primaryButton} href="https://d35ag17soow82e.cloudfront.net/0.4.5/SpectraLens-macos-0.4.5.dmg">macOS app</a><a className={secondaryButton} href="https://d35ag17soow82e.cloudfront.net/0.4.5/SpectraLens-windows-0.4.5.msi">Windows app</a></div><h3>Quick start</h3><ol><li>Add and select the DIA raw files to inspect.</li><li>Use the precursor toolbar to enter peptide sequences and optional charge states.</li><li>Select precursors, review settings, then run targeted extraction.</li><li>Inspect iRT-RT, spectra, MS1 XIC, and MS2 XIC views before exporting results.</li></ol><h3>Precursor input</h3><p>Use one sequence per line or commas between entries. Add a charge suffix such as <code>PEPTIDESEQ.2</code>; use UniMod notation such as <code>C(UniMod:4)</code> for modifications.</p><h3>Support</h3><p>Ask questions in <a className="font-semibold text-brand" href="https://github.com/bionsight/SpectraLens/discussions">GitHub Discussions</a> or report reproducible problems through <a className="font-semibold text-brand" href="https://github.com/bionsight/SpectraLens/issues">GitHub Issues</a>.</p></article><aside className="grid content-start gap-4"><img className="rounded-xl border border-slate-200" src="/images/spectralens/select_raw_files.png" alt="Raw file selection in SpectraLens" loading="lazy" /><img className="rounded-xl border border-slate-200" src="/images/spectralens/fill_sequences.png" alt="Precursor sequence input in SpectraLens" loading="lazy" /></aside></div></section>
  </>
}
