/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as SpectralensRouteImport } from './routes/spectralens'
import { Route as BenchmarksIndexRouteImport } from './routes/benchmarks.index'
import { Route as BenchmarksSlugRouteImport } from './routes/benchmarks.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectralensRoute = SpectralensRouteImport.update({
  id: '/spectralens',
  path: '/spectralens',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksIndexRoute = BenchmarksIndexRouteImport.update({
  id: '/benchmarks/',
  path: '/benchmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksSlugRoute = BenchmarksSlugRouteImport.update({
  id: '/benchmarks/$slug',
  path: '/benchmarks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/spectralens': typeof SpectralensRoute
  '/benchmarks/$slug': typeof BenchmarksSlugRoute
  '/benchmarks/': typeof BenchmarksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/spectralens': typeof SpectralensRoute
  '/benchmarks/$slug': typeof BenchmarksSlugRoute
  '/benchmarks': typeof BenchmarksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/spectralens': typeof SpectralensRoute
  '/benchmarks/$slug': typeof BenchmarksSlugRoute
  '/benchmarks/': typeof BenchmarksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/spectralens'
    | '/benchmarks/$slug'
    | '/benchmarks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/spectralens'
    | '/benchmarks/$slug'
    | '/benchmarks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/spectralens'
    | '/benchmarks/$slug'
    | '/benchmarks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  SpectralensRoute: typeof SpectralensRoute
  BenchmarksSlugRoute: typeof BenchmarksSlugRoute
  BenchmarksIndexRoute: typeof BenchmarksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectralens': {
      id: '/spectralens'
      path: '/spectralens'
      fullPath: '/spectralens'
      preLoaderRoute: typeof SpectralensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks/': {
      id: '/benchmarks/'
      path: '/benchmarks'
      fullPath: '/benchmarks/'
      preLoaderRoute: typeof BenchmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks/$slug': {
      id: '/benchmarks/$slug'
      path: '/benchmarks/$slug'
      fullPath: '/benchmarks/$slug'
      preLoaderRoute: typeof BenchmarksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  SpectralensRoute: SpectralensRoute,
  BenchmarksSlugRoute: BenchmarksSlugRoute,
  BenchmarksIndexRoute: BenchmarksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
